### ISSUE TITLE
set lower gas

### ISSUE THREAD

**Issue by tony-armstrong** [b2network/b2-zkevm-node#18]
> L2GasPricer: it fetches the L1 gas price and applies some formula to calculate the gas price that will be suggested for the users to use for paying fees on L2. The suggestions are stored on the `pool`, and will be consumed by the `rpc`

set default gasprice see: https://github.com/b2network/b2-zkevm-node/blob/a9455e1da8f670963a0b1017287885ffcec9bd1a/test/config/test.node.config.toml#L156

**Comment by frankgululu** [comment]
Changed
