### ISSUE TITLE
fatal error: TRUSTED REORG DETECTED

### ISSUE THREAD

**Issue by tony-armstrong** [b2network/b2-zkevm-node#23]
1. the log when the error first occurred was not saved
    ```bash
    2023-12-20T19:47:37.957+0800    ERROR   synchronizer/synchronizer.go:1820       halting the Synchronizer        {"pid": 1, "version": "v0.4.0-RC6-26-g87902b47"}
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).halt
            /src/synchronizer/synchronizer.go:1820
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).checkTrustedState
            /src/synchronizer/synchronizer.go:791
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processSequenceBatches
            /src/synchronizer/synchronizer.go:1020
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
            /src/synchronizer/synchronizer.go:583
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
            /src/synchronizer/synchronizer.go:423
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
            /src/synchronizer/synchronizer.go:327
    main.runSynchronizer
            /src/cmd/run.go:325
    2023-12-20T19:47:42.958+0800    ERROR   synchronizer/synchronizer.go:1819       fatal error: TRUSTED REORG DETECTED! Batch: 2%!(EXTRA string=
    /src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
    /src/log/log.go:251 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
    /src/synchronizer/synchronizer.go:1819 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).halt()
    /src/synchronizer/synchronizer.go:791 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).checkTrustedState()
    /src/synchronizer/synchronizer.go:1020 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processSequenceBatches()
    /src/synchronizer/synchronizer.go:583 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange()
    /src/synchronizer/synchronizer.go:423 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential()
    /src/synchronizer/synchronizer.go:327 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
    /src/cmd/run.go:325 main.runSynchronizer()
    )       {"pid": 1, "version": "v0.4.0-RC6-26-g87902b47"}
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).halt
            /src/synchronizer/synchronizer.go:1819
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).checkTrustedState
            /src/synchronizer/synchronizer.go:791
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processSequenceBatches
            /src/synchronizer/synchronizer.go:1020
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
            /src/synchronizer/synchronizer.go:583
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocksSequential
            /src/synchronizer/synchronizer.go:423
    github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
            /src/synchronizer/synchronizer.go:327
    main.runSynchronizer
            /src/cmd/run.go:325
    2023-12-20T19:47:42.958+0800    ERROR   synchronizer/synchronizer.go:1820       halting the Synchronizer        {"pid": 1, "version": "v0.4.0-RC6-26-g87902b47"}
    ```
1. related issue:
    1. 0xPolygonHermez/zkevm-node#2740
    2. 0xPolygonHermez/zkevm-node#1676
    3. 0xPolygonHermez/zkevm-node#828
    4. 0xPolygonHermez/zkevm-node#796
2. https://docs.polygon.technology/pos/operate-node/validator/kb/known-issues/?h=reorg#error-impossible-reorg-please-file-an-issue
3. how to reproduce and solve it?

**Comment by tony-armstrong** [comment]
state_root is calculated through grpc ProcessBatch call https://github.com/b2network/b2-zkevm-node/blob/d16f73da545f51576f5976b0f23de742e0ac8e58/state/batch.go#L255

impl in prover https://github.com/b2network/b2-zkevm-prover/blob/806fc234249e1ed74bbdf1a4dbc79a268a034320/src/service/executor/executor_service.cpp#L15

**Comment by threewebcode** [comment]
Context:

1. The pool schema has transaction table and the records can be deleted by hash.
2. L2 can be also reorganized.

**Comment by threewebcode** [comment]
/*
This function will check if there is a reorg.
As input param needs the last ethereum block synced. Retrieve the block info from the blockchain
to compare it with the stored info. If hash and hash parent matches, then no reorg is detected and return a nil.
If hash or hash parent don't match, reorg detected and the function will return the block until the sync process
must be reverted. Then, check the previous ethereum block synced, get block info from the blockchain and check
hash and has parent. This operation has to be done until a match is found.
*/

**Comment by threewebcode** [comment]
```
// CountReorgs returns the number of reorgs
func (p *PostgresStorage) CountReorgs(ctx context.Context, dbTx pgx.Tx) (uint64, error) {
        const countReorgsSQL = "SELECT COUNT(*) FROM state.trusted_reorg"

        var count uint64
        q := p.getExecQuerier(dbTx)
        err := q.QueryRow(ctx, countReorgsSQL).Scan(&count)
        if err != nil {
                return 0, err
        }
        return count, nil
}
```

**Comment by threewebcode** [comment]
```
func (s *ClientSynchronizer) checkTrustedState(batch state.Batch, tBatch *state.Batch, newRoot common.Hash, dbTx pgx.Tx) bool {
        //Compare virtual state with trusted state
        var reorgReasons strings.Builder
        if newRoot != tBatch.StateRoot {
                log.Warnf("Different field StateRoot. Virtual: %s, Trusted: %s\n", newRoot.String(), tBatch.StateRoot.String())
                reorgReasons.WriteString(fmt.Sprintf("Different field StateRoot. Virtual: %s, Trusted: %s\n", newRoot.String(), tBatch.StateR
oot.String()))
        }
        if hex.EncodeToString(batch.BatchL2Data) != hex.EncodeToString(tBatch.BatchL2Data) {
                log.Warnf("Different field BatchL2Data. Virtual: %s, Trusted: %s\n", hex.EncodeToString(batch.BatchL2Data), hex.EncodeToStrin
g(tBatch.BatchL2Data))
                reorgReasons.WriteString(fmt.Sprintf("Different field BatchL2Data. Virtual: %s, Trusted: %s\n", hex.EncodeToString(batch.Batc
hL2Data), hex.EncodeToString(tBatch.BatchL2Data)))
        }
        if batch.GlobalExitRoot.String() != tBatch.GlobalExitRoot.String() {
                log.Warnf("Different field GlobalExitRoot. Virtual: %s, Trusted: %s\n", batch.GlobalExitRoot.String(), tBatch.GlobalExitRoot.
String())
                reorgReasons.WriteString(fmt.Sprintf("Different field GlobalExitRoot. Virtual: %s, Trusted: %s\n", batch.GlobalExitRoot.Strin
g(), tBatch.GlobalExitRoot.String()))
        }
        if batch.Timestamp.Unix() != tBatch.Timestamp.Unix() {
                log.Warnf("Different field Timestamp. Virtual: %d, Trusted: %d\n", batch.Timestamp.Unix(), tBatch.Timestamp.Unix())
                reorgReasons.WriteString(fmt.Sprintf("Different field Timestamp. Virtual: %d, Trusted: %d\n", batch.Timestamp.Unix(), tBatch.
Timestamp.Unix()))
        }
        if batch.Coinbase.String() != tBatch.Coinbase.String() {
                log.Warnf("Different field Coinbase. Virtual: %s, Trusted: %s\n", batch.Coinbase.String(), tBatch.Coinbase.String())
                reorgReasons.WriteString(fmt.Sprintf("Different field Coinbase. Virtual: %s, Trusted: %s\n", batch.Coinbase.String(), tBatch.
Coinbase.String()))
        }
        if reorgReasons.Len() > 0 {
                reason := reorgReasons.String()

                if tBatch.StateRoot == (common.Hash{}) {
                        log.Warnf("incomplete trusted batch %d detected. Syncing full batch from L1", tBatch.BatchNumber)
                } else {
                        log.Warnf("missmatch in trusted state detected for Batch Number: %d. Reasons: %s", tBatch.BatchNumber, reason)
                }
                if s.isTrustedSequencer {
                        s.halt(s.ctx, fmt.Errorf("TRUSTED REORG DETECTED! Batch: %d", batch.BatchNumber))
                }
                // Store trusted reorg register
                tr := state.TrustedReorg{
                        BatchNumber: tBatch.BatchNumber,
                        Reason:      reason,
                }
                err := s.state.AddTrustedReorg(s.ctx, &tr, dbTx)
                if err != nil {
                        log.Error("error storing tursted reorg register into the db. Error: ", err)
                }
                return true
        }
        return false
}

```

**Comment by threewebcode** [comment]
Trace:  

1. start(cliCtx *cli.Context) -> runSynchronizer -> ClientSynchronizer.Sync -> syncBlocksSequential

2.  l1_sync_orchestration.go -> l1RollupInfoConsumer.Start -> l1RollupInfoConsumer.step-> processIncommingRollupInfoData -> processUnsafe

3.  syncBlocksSequential/processUnsafe->processBlockRange->processSequenceBatches-> checkTrustedState

**Comment by threewebcode** [comment]
In the Polygon zkEVM system, the terms "batch," "virtual batch," "forced batch," and "verified batch" are used to describe different stages and processes within the system. Let's explore each of these terms in detail:

1. Batch: A batch refers to a collection of transactions that are grouped together for processing and execution within the Polygon zkEVM system. These transactions can be executed almost instantly and are stored in a pending transactions pool [[2]](https://blog.jarrodwatts.com/how-polygon-zkevm-proves-batches-of-transactions). Batching transactions helps improve efficiency and scalability by processing multiple transactions together.

2. Virtual Batch: After the transactions are added to the Layer 2 (L2) state, they are ready to be batched up with other transactions. In the Polygon zkEVM system, these batches are concatenated into a single set of bytes using a Solidity struct called `BatchData` [[2]](https://blog.jarrodwatts.com/how-polygon-zkevm-proves-batches-of-transactions). This struct contains the encoded batch of transactions, along with other relevant information such as the global exit root and timestamps [[2]](https://blog.jarrodwatts.com/how-polygon-zkevm-proves-batches-of-transactions). The virtual batch represents the collection of transactions that are ready to be sequenced and sent to Ethereum L1.

3. Forced Batch: The concept of a forced batch is related to the trusted sequencer in the Polygon zkEVM system. The trusted sequencer is responsible for selecting and executing transactions within the system. In certain scenarios, such as when a transaction is a duplicate or a "double-spend," the sequencer can discard the transaction and prevent it from being included in a batch [[2]](https://blog.jarrodwatts.com/how-polygon-zkevm-proves-batches-of-transactions). This process ensures the integrity and security of the system.

4. Verified Batch: Once the batches of transactions have been sequenced and sent to Ethereum L1, the final step is to generate a zero-knowledge (ZK) proof that verifies the validity of these transactions. Aggregator nodes take the sequenced batches and provide them to the ZK prover, which produces a final SNARK (Succinct Non-interactive ARgument of Knowledge) using the fflonk protocol [[3]](https://medium.com/banana-sdk/demystifying-polygons-zk-evm-part-2-d6d873a6f82c). The resulting ZK proof is then posted on Ethereum L1, providing consolidated finality and inheriting Ethereum's security [[2]](https://blog.jarrodwatts.com/how-polygon-zkevm-proves-batches-of-transactions).

**Comment by threewebcode** [comment]
There is no timestamp column in the virtual_batch table. The virtual batch object's Timestamp field value is copied from other batch or from the contract side. 

To do the validation of trusted batch, the input parameters are virtual batch, trusted batch and new root. During the sequenced batch process, the trusted batch needs to be checked. The original data is from the sequenced batch. The virtual batch and trusted batch are constructed with the sequenced batch. The timestamp field of trusted batch is inherited from the sequenced batch. If the sequenced batch is a forced batch, the forced number is added into the trusted batch. The trusted batch is reloaded by the batch number from the database. If the trusted batch is not existed in the database, the trusted batch is still previous value. 

The trusted batch is retrieved from the batch table in the state schema. The trusted batch is inserted by calling the openBatch function. In terms of data structure, the sequenced batch has not timestamp property. However, the sequenced forced batch has such an attribute. The sequence batch and sequence forced batch are managed by the smart contract. Their data can be queried again the smart contract function. The sequence forced batch's timestamp property is assigned with block timestamp.

**Comment by threewebcode** [comment]
```
	
2023-12-23T15:04:41.254966902+08:00 stderr F {"level":"warn","ts":1703315081.2549024,"caller":"synchronizer/synchronizer.go:788","msg":"missmatch in trusted state detected for Batch Number: 42. Reasons: Different field Timestamp. Virtual: 1703314667, Trusted: 1703314747\n","pid":1,"version":"v0.4.0-RC6-26-g87902b47"}

	
2023-12-23T15:04:56.819168559+08:00 stderr F {"level":"info","ts":1703315096.8190465,"caller":"ethtxmanager/ethtxmanager.go:685","msg":"waiting for monitored tx to get confirmed, status: sent","pid":1,"version":"v0.4.0-RC6-26-g87902b47","owner":"sequencer","monitoredTxId":"sequence-from-41-to-42"}

2023-12-23T15:04:34.665571112+08:00 stderr F {"level":"info","ts":1703315074.665499,"caller":"sequencesender/sequencesender.go:103","msg":"sending sequences to L1. From batch 42 to batch 43","pid":1,"version":"v0.4.0-RC6-26-g87902b47"}

2023-12-23T15:04:19.638378434+08:00 stderr F {"level":"info","ts":1703315059.6383348,"caller":"sequencesender/sequencesender.go:289","msg":"Done building sequences, selected batches to 1. Batch 2 excluded due to unknown error: rpc error: code = Unknown desc = execution reverted","pid":1,"version":"v0.4.0-RC6-26-g87902b47"}
```

**Comment by threewebcode** [comment]
1703314747  => GMT: Saturday, December 23, 2023 6:59:07 AM

1703314667 => GMT: Saturday, December 23, 2023 6:57:47 AM

**Comment by threewebcode** [comment]
```
2023-12-23T15:04:59.838392563+08:00 stderr F {"level":"info","ts":1703315099.8382535,"caller":"ethtxmanager/ethtxmanager.go:685","msg":"waiting for monitored tx to get confirmed, status: sent","pid":1,"version":"v0.4.0-RC6-26-g87902b47","owner":"sequencer","monitoredTxId":"sequence-from-41-to-42"}
```

**Comment by threewebcode** [comment]
```
	
2023-12-23T15:03:42.803452368+08:00 stderr F {"level":"info","ts":1703315022.8033383,"caller":"sequencesender/sequencesender.go:188","msg":"Handling estimage gas send sequence error: rpc error: code = Unknown desc = execution reverted","pid":1,"version":"v0.4.0-RC6-26-g87902b47"}
```

**Comment by threewebcode** [comment]
The logs from grafana:

https://grafana.bsquared.network/explore?orgId=1&left=%7B%22datasource%22:%22YmxX-2DSz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22b2%5C%22,%20app%3D%5C%22zkevm-sync%5C%22%7D%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221703315040000%22,%22to%22:%221703315100000%22%7D%7D

**Comment by threewebcode** [comment]
2023-12-23T15:04:35.038205803+08:00 stderr F {"level":"info","ts":1703315075.038125,"caller":"ethtxmanager/ethtxmanager.go:419","msg":"signed tx sent to the network: 0x13ef95707747b24c8c9cc85e117297a4a335613e89c3e7d60cccbb45a2c8ddcb","pid":1,"version":"v0.4.0-RC6-26-g87902b47","owner":"sequencer","monitoredTxId":"sequence-from-41-to-42","createdAt":1703315074.681917,"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0x67d269191c92Caf3cD7723F116c85e6E9bf55933"}

**Comment by threewebcode** [comment]
```
select status from state.monitored_txs where owner = 'sequencer' and    id = 'sequence-from-41-to-42';
```

**Comment by threewebcode** [comment]
```
select owner, id from state.monitored_txs where owner='sequencer' order by created_at desc;

psql state_db state_user -c "select owner, id from state.monitored_txs where owner='sequencer' order by created_at desc LIMIT 2;"

psql --username=state_user --list

psql prover_db prover_user -c "\dt"
psql prover_db prover_user -c "select * from state.nodes;"
psql prover_db prover_user -c "select * from state.program;"

SELECT * FROM pool.transaction;

SELECT count(*) FROM pool.transaction;

SELECT is_claims, is_wip, failed_reason FROM pool.transaction WHERE is_wip = TRUE;

SELECT * FROM public.event ORDER BY id DESC;

SELECT * FROM state.virtual_batch ORDER BY batch_num DESC;
SELECT * FROM state.verified_batch ORDER BY batch_num DESC;
SELECT * FROM state.transaction ORDER BY l2_block_num DESC;
SELECT batch_num, count(block_num) FROM state.l2block GROUP BY batch_num;

SELECT * FROM state.block ORDER BY block_num DESC;

SELECT * FROM state.block ORDER BY received_at DESC;

SELECT * FROM state.batch ORDER BY batch_num DESC;
SELECT * FROM state.batch ORDER BY timestamp DESC;

SELECT forced_batch_num FROM state.batch;


```

**Comment by threewebcode** [comment]
Reasoning:

1. The b2-node's block hash is computed from its header;
2. The zkevm-node's block hash is calculated from the go-ethereum header
3. Their mathematical steps are different.

b2-node: https://github.com/b2network/b2-node/blob/main/rpc/types/utils.go
go-ethereum: https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go

**Comment by threewebcode** [comment]
The code patch is committed to solve this issue.

**Comment by threewebcode** [comment]
solved in this commit: https://github.com/b2network/b2-zkevm-node/commit/31e97d0170479efd9696c6d46640342fc3a1755c

**Comment by threewebcode** [comment]
```
#!/bin/bash

containers=("zkevm-aggregator" "zkevm-sequence-sender" "zkevm-sequencer" "zkevm-eth-tx-manager" "zkevm-sync" "zkevm-mock-l1-network" "zkevm-pool-db" "zkevm-state-db")

stopped_containers=()

stop_random_container() {
  local random_index=$((RANDOM % ${#containers[@]}))
  local random_container="${containers[random_index]}"
  docker stop "$random_container" >/dev/null 2>&1
  stopped_containers+=("$random_container")
  echo "Container $random_container stopped."
}

start_stopped_containers() {
  for container in "${stopped_containers[@]}"; do
    docker start "$container" >/dev/null 2>&1
    echo "Container $container started."
  done
  stopped_containers=()
}

for ((i=0; i<360; i+=5)); do
  echo "Waiting for 5 seconds..."
  sleep 5
  if ((i % 10 == 0)); then
    start_stopped_containers
  else
    stop_random_container
  fi
done

start_stopped_containers
```
